[archive]
build_output_dir = 'Built'
archive_location = '\\nirvana\Measurements\VeriStandAddons\scan_engine_modules'

[projects.modules]
path = 'Source\Modules.lvproj'

[[build.steps]]
name = 'Scan Engine Module Libraries'
type = 'lvBuildSpecAllTargets'
project = '{modules}'
build_spec = 'Modules'

[[build.steps]]
name = 'Scan Engine Remote IO Libraries'
type = 'lvBuildSpecAllTargets'
project = '{modules}'
target = 'My Computer'
build_spec = 'NI ECAT Remote IO'
